 export const JobData = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova",
    location: "Remote",
    type: "Full Time",
    experience: "Fresher",
    salary: "₹4–6 LPA",
    description: "Work on modern UI using React and Next.js."
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "CodeCraft",
    location: "Bangalore",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹6–10 LPA",
    description: "Build APIs using Node.js and MongoDB."
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "DataStack",
    location: "Hyderabad",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹10–15 LPA",
    description: "Handle frontend and backend for scalable products."
  },
  {
    id: 4,
    title: "UI/UX Designer",
    company: "PixelWorks",
    location: "Mumbai",
    type: "Part Time",
    experience: "1–3 Years",
    salary: "₹5–7 LPA",
    description: "Design intuitive interfaces using Figma."
  },
  {
    id: 5,
    title: "Data Analyst",
    company: "InsightLabs",
    location: "Delhi",
    type: "Full Time",
    experience: "Fresher",
    salary: "₹4–6 LPA",
    description: "Analyze datasets and generate insights."
  },

  // ---------- 6–20 ----------
  {
    id: 6,
    title: "AI Engineer",
    company: "BrainAI",
    location: "Remote",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹12–18 LPA",
    description: "Develop AI-powered solutions and APIs."
  },
  {
    id: 7,
    title: "ML Engineer",
    company: "NextGen Labs",
    location: "Pune",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹15–22 LPA",
    description: "Train and deploy ML models."
  },
  {
    id: 8,
    title: "DevOps Engineer",
    company: "Cloudify",
    location: "Bangalore",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹8–12 LPA",
    description: "Manage CI/CD pipelines and cloud infra."
  },
  {
    id: 9,
    title: "Mobile App Developer",
    company: "AppVerse",
    location: "Chennai",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹6–9 LPA",
    description: "Develop Android and iOS applications."
  },
  {
    id: 10,
    title: "QA Engineer",
    company: "SoftEdge",
    location: "Kolkata",
    type: "Full Time",
    experience: "Fresher",
    salary: "₹3–5 LPA",
    description: "Test applications and ensure quality."
  },

  // ---------- 11–50 ----------
  {
    id: 11,
    title: "Frontend Intern",
    company: "TechNova",
    location: "Remote",
    type: "Internship",
    experience: "Fresher",
    salary: "₹15k/month",
    description: "Learn React and UI development."
  },
  {
    id: 12,
    title: "Backend Intern",
    company: "DataStack",
    location: "Bangalore",
    type: "Internship",
    experience: "Fresher",
    salary: "₹18k/month",
    description: "Assist in backend API development."
  },
  {
    id: 13,
    title: "Full Stack Intern",
    company: "InnoSoft",
    location: "Pune",
    type: "Internship",
    experience: "Fresher",
    salary: "₹20k/month",
    description: "Work across frontend and backend."
  },
  {
    id: 14,
    title: "Product Designer",
    company: "CreativeLabs",
    location: "Mumbai",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹7–10 LPA",
    description: "Design product workflows and UI."
  },
  {
    id: 15,
    title: "System Engineer",
    company: "FutureLoop",
    location: "Hyderabad",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹9–13 LPA",
    description: "Maintain system infrastructure."
  },

  // ---------- 51–100 ----------
  {
    id: 51,
    title: "Cloud Engineer",
    company: "Cloudify",
    location: "Remote",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹10–14 LPA",
    description: "Manage cloud-based solutions."
  },
  {
    id: 52,
    title: "Security Analyst",
    company: "SecureNet",
    location: "Delhi",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹12–18 LPA",
    description: "Ensure application and network security."
  },
  {
    id: 53,
    title: "Database Administrator",
    company: "DataCore",
    location: "Bangalore",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹8–12 LPA",
    description: "Manage and optimize databases."
  },
  {
    id: 54,
    title: "Software Tester",
    company: "BugTrack",
    location: "Pune",
    type: "Part Time",
    experience: "Fresher",
    salary: "₹4–6 LPA",
    description: "Manual and automated testing."
  },
  {
    id: 55,
    title: "Technical Support Engineer",
    company: "HelpDesk Pro",
    location: "Chennai",
    type: "Full Time",
    experience: "Fresher",
    salary: "₹3–5 LPA",
    description: "Provide technical assistance to users."
  },
];

export const savedJobsData = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "PixelCraft",
    location: "Bangalore",
    type: "Full Time",
    experience: "2+ Years",
    salary: "₹6–9 LPA",
    description: "Build responsive UI using React and Tailwind CSS.",
    savedDate: "05 Sep 2026",
    applicationEndDate: "25 Sep 2026",
  },
  {
    id: 2,
    title: "Backend Engineer",
    company: "CloudNova",
    location: "Pune",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹8–12 LPA",
    description: "Design scalable APIs and manage databases.",
    savedDate: "06 Sep 2026",
    applicationEndDate: "28 Sep 2026",
  },
  {
    id: 3,
    title: "MERN Stack Developer",
    company: "DevSphere",
    location: "Remote",
    type: "Remote",
    experience: "1–3 Years",
    salary: "₹5–8 LPA",
    description: "Work across frontend and backend using MERN stack.",
    savedDate: "07 Sep 2026",
    applicationEndDate: "20 Sep 2026",
  },
  {
    id: 4,
    title: "System Engineer",
    company: "FutureLoop",
    location: "Hyderabad",
    type: "Full Time",
    experience: "3+ Years",
    salary: "₹9–13 LPA",
    description: "Maintain and optimize system infrastructure.",
    savedDate: "08 Sep 2026",
    applicationEndDate: "30 Sep 2026",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "DesignMint",
    location: "Mumbai",
    type: "Full Time",
    experience: "2–4 Years",
    salary: "₹7–10 LPA",
    description: "Create intuitive interfaces and user flows.",
    savedDate: "09 Sep 2026",
    applicationEndDate: "22 Sep 2026",
  },
  {
    id: 6,
    title: "DevOps Engineer",
    company: "InfraWorks",
    location: "Bangalore",
    type: "Full Time",
    experience: "4+ Years",
    salary: "₹12–18 LPA",
    description: "Automate deployments and manage cloud infrastructure.",
    savedDate: "10 Sep 2026",
    applicationEndDate: "05 Oct 2026",
  },
  {
    id: 7,
    title: "Data Analyst",
    company: "InsightIQ",
    location: "Gurgaon",
    type: "Full Time",
    experience: "1–3 Years",
    salary: "₹6–9 LPA",
    description: "Analyze data to generate business insights.",
    savedDate: "11 Sep 2026",
    applicationEndDate: "27 Sep 2026",
  },
  {
    id: 8,
    title: "Software Tester",
    company: "QualityFirst",
    location: "Chennai",
    type: "Full Time",
    experience: "2+ Years",
    salary: "₹5–7 LPA",
    description: "Test applications and ensure product quality.",
    savedDate: "12 Sep 2026",
    applicationEndDate: "24 Sep 2026",
  },
  {
    id: 9,
    title: "AI/ML Engineer",
    company: "NeuroStack",
    location: "Remote",
    type: "Remote",
    experience: "3+ Years",
    salary: "₹15–22 LPA",
    description: "Build and deploy machine learning models.",
    savedDate: "13 Sep 2026",
    applicationEndDate: "10 Oct 2026",
  },
  {
    id: 10,
    title: "Product Manager",
    company: "BuildFlow",
    location: "Bangalore",
    type: "Full Time",
    experience: "4–6 Years",
    salary: "₹18–25 LPA",
    description: "Own product roadmap and feature delivery.",
    savedDate: "14 Sep 2026",
    applicationEndDate: "03 Oct 2026",
  },
  {
    id: 11,
    title: "Cyber Security Analyst",
    company: "SecureNet",
    location: "Noida",
    type: "Full Time",
    experience: "3–5 Years",
    salary: "₹10–14 LPA",
    description: "Monitor systems and prevent security threats.",
    savedDate: "15 Sep 2026",
    applicationEndDate: "01 Oct 2026",
  },
  {
    id: 12,
    title: "Mobile App Developer",
    company: "AppForge",
    location: "Kochi",
    type: "Full Time",
    experience: "2+ Years",
    salary: "₹6–10 LPA",
    description: "Develop Android and iOS applications.",
    savedDate: "16 Sep 2026",
    applicationEndDate: "29 Sep 2026",
  },
];




